# Generated by Django 5.1 on 2024-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="year_born_temp",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Временное поле для преобразования года рождения",
                null=True,
                verbose_name="Временный год рождения",
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание породы",
                null=True,
                verbose_name="Описание породы",
            ),
        ),
    ]
