# Generated by Django 5.1 on 2024-08-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_parent_year_born_temp_alter_breed_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="year_born",
        ),
    ]
