# Generated by Django 4.2.2 on 2024-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0007_dog_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Статья")),
                ("body", models.TextField(verbose_name="Сообщение")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
