# Generated by Django 4.2.2 on 2024-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0008_test"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parent",
            options={
                "ordering": ["breed", "name"],
                "permissions": [
                    ("can_edit_bread", "Can edit bread"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Собака родитель",
                "verbose_name_plural": "Собаки родители",
            },
        ),
        migrations.AlterModelOptions(
            name="test",
            options={
                "permissions": [("set_published", "Can publish posts")],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AddField(
            model_name="dog",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание собаки",
                null=True,
                verbose_name="Описание собаки",
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
