# Generated by Django 4.2.2 on 2024-09-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0009_alter_parent_options_alter_test_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dog",
            options={
                "ordering": ["breed", "name"],
                "permissions": [
                    ("can_edit_bread", "Can edit bread"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Собака",
                "verbose_name_plural": "Собаки",
            },
        ),
    ]
